In [147]:
import numpy as np
from numpy import linalg as LA
a = [3,1,1,1,3,2,1,1,4]
A=np.reshape(a,(3,3))
B=[3,0,7]
#B=np.reshape(B,(3,1))
IG=[0.0,0.0,0.0] 
tol = 1e-6
itr=50
#np.transpose(B)

In [157]:
def GS(a,b, initial_guess ,tol,itr):
    n=len(a)
    x=initial_guess.copy() 
    #x=initial_guess
    print(a)
    print(b)
    for k in range(1,itr):
        xo=x.copy()
        print(f"Iteration {k}: {xo}")
        for i in range(n):
            sum1=np.dot(a[i,:i],x[:i])
            sum2=np.dot(a[i,(i+1):],xo[(i+1):])
            x[i]=(b[i]-sum1-sum2)/a[i,i]
        if(np.allclose(x,xo,tol)):
            print(f"Solution: {x}")
            print(k)
            break
    return x   
    
    
    

In [158]:
y=GS(A,B, IG ,tol,itr)

[[3 1 1]
 [1 3 2]
 [1 1 4]]
[3, 0, 7]
Iteration 1: [0.0, 0.0, 0.0]
Iteration 2: [1.0, -0.3333333333333333, 1.5833333333333333]
Iteration 3: [0.5833333333333334, -1.25, 1.9166666666666667]
Iteration 4: [0.7777777777777777, -1.537037037037037, 1.9398148148148149]
Iteration 5: [0.8657407407407408, -1.5817901234567902, 1.9290123456790123]
Iteration 6: [0.8842592592592592, -1.580761316872428, 1.9241255144032923]
Iteration 7: [0.8855452674897119, -1.5779320987654322, 1.92309670781893]
Iteration 8: [0.8849451303155007, -1.5770461819844535, 1.9230252629172382]
Iteration 9: [0.8846736396890718, -1.576908055174516, 1.923058603871361]
Iteration 10: [0.8846164837677183, -1.5769112305034803, 1.9230736866839404]
Iteration 11: [0.8846125146065132, -1.5769199626581314, 1.9230768620129046]
Iteration 12: [0.8846143668817422, -1.5769226969691836, 1.9230770825218604]
Solution: [0.8846152048157744, -1.5769231232864984, 1.923076979617681]
12


In [167]:
def jacobi_itr(a,b, initial_guess ,tol,itr):
    n=len(a)
    x=initial_guess.copy() 
    #x=initial_guess
    print(a)
    print(b)
    for k in range(1,itr):
        xo=x.copy()
        print(f"Iteration {k}: {xo}")
        for i in range(n):
            sum1=np.dot(a[i,:i],xo[:i])
            sum2=np.dot(a[i,(i+1):],xo[(i+1):])
            x[i]=(b[i]-sum1-sum2)/a[i,i]
        if(np.allclose(x,xo,tol)):
            print(f"Solution: {x}")
            print(k)
            break
    return x

In [168]:
y=jacobi_itr(A,B, IG ,tol,itr)

[[3 1 1]
 [1 3 2]
 [1 1 4]]
[3, 0, 7]
Iteration 1: [0.0, 0.0, 0.0]
Iteration 2: [1.0, 0.0, 1.75]
Iteration 3: [0.4166666666666667, -1.5, 1.5]
Iteration 4: [1.0, -1.1388888888888888, 2.0208333333333335]
Iteration 5: [0.7060185185185185, -1.6805555555555556, 1.7847222222222223]
Iteration 6: [0.9652777777777777, -1.4251543209876543, 1.9936342592592593]
Iteration 7: [0.8105066872427983, -1.6508487654320987, 1.8649691358024691]
Iteration 8: [0.9286265432098766, -1.5134816529492454, 1.960085519547325]
Iteration 9: [0.8511320444673068, -1.6162658607681755, 1.8962137774348422]
Iteration 10: [0.9066840277777777, -1.547853199778997, 1.941283454075217]
Iteration 11: [0.86885658190126, -1.5964169786427373, 1.9102922930003048]
Iteration 12: [0.8953748952141442, -1.56314705596729, 1.9318900991853694]
Iteration 13: [0.8770856522606403, -1.586385031194961, 1.9169430401882865]
Iteration 14: [0.8898139970022249, -1.5703239108790712, 1.9273248447335802]
Iteration 15: [0.8809996887151637, -1.5814878954897

In [164]:
IG

[0.0, 0.0, 0.0]